spring:
  application:
    name: best-practices
  datasource:
    url: jdbc:postgresql://postgresql:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    port: 5672
    connection-timeout: 2000
  liquibase.change-log: classpath:db/changeLog.sql

management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always