apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: department-service
build:
  artifacts:
  - image: piomin/department-service
    jib:
      args:
      - -Pjib
  tagPolicy:
    gitCommit: {}
